tiles:
        - filename: "images/cross.png"
          edges: [1,1,1,1]
        - filename: "images/t-junction.png"
          edges: [0,1,1,1]
        - filename: "images/turn.png"
          edges: [0,1,1,0]
        - filename: "images/empty.png"
          edges: [0,0,0,0]
        - filename: "images/deadend.png"
          edges: [0,0,1,0]
